# Author: Nuno Cancelo - Devoteam (nuno.cancelo@devoteam.com)
# Date: October 2024
# Description: This pipeline automates the process of building and publishing 
#              Docker Image artifacts to the Azure Container Registry (ACR)
#              and deploying to DEV and PRD environment.

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  imageRepository: ''
  containerRegistry: ''
  containerRegistryName: 'acrinvgenadevneu001'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Development Resources
  azureSubscriptionDev: ''
  resourceGroupDev: ''
  containerAppNameDev: ''

  # Production Resources
  azureSubscriptionPrd: ''
  resourceGroupPrd: ''
  containerAppNamePrd: ''


  # Agent VM image name
  vmImageName: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: '$(containerRegistryName)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)
          latest
    - script: |
        last_scanned="last_scanned-$(date +%Y%m%d)"
        echo "##vso[build.addbuildtag]$(tag)-$last_scanned"
      displayName: 'Apply last scanned tag'

- stage: DeployToDev
  dependsOn: Build
  jobs:
  - deployment: DeployToDev
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: '$(azureSubscriptionDev)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az containerapp update --name $(containerAppNameDev) --resource-group $(resourceGroupDev) --image $(containerRegistryName).azurecr.io/$(imageRepository):$(tag)

- stage: DeployToProd
  dependsOn: DeployToDev
  jobs:
  - deployment: DeployToProd
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: '$(azureSubscriptionPrd)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az containerapp update --name $(containerAppNamePrd) --resource-group $(resourceGroupPrd) --image $(containerRegistryName).azurecr.io/$(imageRepository):$(tag)
